version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb 
    ports:
    - 27017:27017
    volumes:
    - ./mongodb/data:/data/db 
  flask-service:
    build:
      context: ./flask 
      dockerfile: Dockerfile
    restart: always 
    container_name: flask 
    depends_on: 
      - mongodb
    ports:
      - 5003:5003
    environment:
      -  "MONGO_HOSTNAME=mongodb"